name: zeehome
description: ZeeHome project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  eventsource: ^0.4.0
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  intl: ^0.18.0
  location: ^4.4.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  namefully: ^0.2.0
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.1.0
  email_validator: ^2.1.17
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  infinite_scroll_pagination: ^3.2.0
  socket_io_client: ^2.0.2
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0
  firebase_core: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/background2.jpg
  - assets/images/app-bg.jpg
  - assets/images/signin.jpeg
  - assets/images/login3.jpeg
  - assets/images/signin2.jpg
  
  - assets/logo.png
  - assets/icon/back_arrow.svg
  - assets/icon/heart-icon.svg
  - assets/icon/flower.svg
  - assets/icon/icon_2.svg
  - assets/icon/icon_3.svg
  - assets/icon/icon_4.svg
  - assets/icon/menu.svg
  - assets/icon/more.svg
  - assets/icon/search.svg
  - assets/icon/sun.svg
  - assets/icon/user-icon.svg
  - assets/icon/location_pin.svg
  - assets/icon/money-bag.png
  - assets/icon/credit-card.png
  - assets/icon/piggy-bank.png
  - assets/images/background_app.png
  - assets/images/search.png
  - assets/images/user.png
  - assets/images/houseList.png
  - assets/images/createHouse.png
  - assets/images/payment.png
  - assets/images/chat.png
  - assets/images/background.jpg
  - assets/images/banking.png
  - assets/images/vnpay.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_app.png"

