// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldn5WAM6FCaHaKpmrvbf2TdccyR6OBgA',
    appId: '1:859884689750:web:3d770525bbf829e45a1ef7',
    messagingSenderId: '859884689750',
    projectId: 'int3509-1',
    authDomain: 'int3509-1.firebaseapp.com',
    databaseURL: 'https://int3509-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'int3509-1.appspot.com',
    measurementId: 'G-XB8XMFX7CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7uiJ0VO3EeuJxeq7EDcKHebrjyshOrE',
    appId: '1:859884689750:android:c691f6a79c09e1405a1ef7',
    messagingSenderId: '859884689750',
    projectId: 'int3509-1',
    databaseURL: 'https://int3509-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'int3509-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxe2sJpYRMXMTLWN54lGfgxELr0DkJFGk',
    appId: '1:859884689750:ios:7450c43dbd031c065a1ef7',
    messagingSenderId: '859884689750',
    projectId: 'int3509-1',
    databaseURL: 'https://int3509-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'int3509-1.appspot.com',
    iosClientId: '859884689750-026h9476a9102enu5dfu6b81ckdu90j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeeHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxe2sJpYRMXMTLWN54lGfgxELr0DkJFGk',
    appId: '1:859884689750:ios:7450c43dbd031c065a1ef7',
    messagingSenderId: '859884689750',
    projectId: 'int3509-1',
    databaseURL: 'https://int3509-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'int3509-1.appspot.com',
    iosClientId: '859884689750-026h9476a9102enu5dfu6b81ckdu90j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeeHome',
  );
}
